apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-client
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-client
  template:
    metadata:
      labels:
        app: spark-client
    spec:
      serviceAccountName: spark
      containers:
        - name: spark
          image: kafka-to-minio:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "sleep infinity"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spark
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role